version: 0.2

phases:
  pre_build:
    commands:
      - echo check aws cli version
      - aws --version
  build:
    commands:
      - echo Create Lambda Function zip
      - bash aws/script/create_zip_files.sh
      - echo Create Step Functions Distributed Map Input Parameter
      - bash aws/script/create_map_inputs.sh
  post_build:
    commands:
      - echo AWS resource copy to S3
      - aws s3 sync --exact-timestamps --delete aws/stepfunctions/ s3://quark-cicd-test/stepfunctions/
      - aws s3 sync --exact-timestamps --delete aws/s3/create_table_query/ s3://quark-cicd-test/s3/create_table_query/

      - echo datamart build for cloudformation
      - aws cloudformation package --template-file aws/cloudformation/datamart-cicd.yml --s3-bucket quark-cicd-test --s3-prefix cloudformation/package --output-template-file /tmp/cloudformation-datamart-cicd.yml
      - aws cloudformation deploy --force-upload --no-fail-on-empty-changeset --template-file /tmp/cloudformation-datamart-cicd.yml --stack-name datamart-cicd --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM
