AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a Step Functions state machine.

Parameters:
    CFnResourceBucket:
        Description: CFn/StepFunctions Source S3 Bucket
        Type: String
        Default: quark-cicd-test
    QueryScanLambda:
        Description: Lambda Function & File name
        Type: String
        Default: athena-query-scan
    DeleteS3ObjLambda:
        Description: Lambda Function & File name
        Type: String
        Default: delete-s3-objects
Resources:
    # IAM Role
    StepFunctionServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: DatamartUpdateRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - states.amazonaws.com
                              - scheduler.amazonaws.com
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns: [arn:aws:iam::aws:policy/AdministratorAccess]
    # Lambda
    AthenaQueryScan:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Sub ${CFnResourceBucket}
                S3Key: !Sub lambda/src/${QueryScanLambda}.zip
            FunctionName: !Sub ${QueryScanLambda}
            Handler: lambda_function.lambda_handler
            Role: !GetAtt StepFunctionServiceRole.Arn
            Runtime: python3.9
            Timeout: 60
    DeleteS3Objects:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: !Sub ${CFnResourceBucket}
                S3Key: !Sub lambda/src/${DeleteS3ObjLambda}.zip
            FunctionName: !Sub ${DeleteS3ObjLambda}
            Handler: lambda_function.lambda_handler
            Role: !GetAtt StepFunctionServiceRole.Arn
            Runtime: python3.9
            Timeout: 60
    # StepFunctions
    StepFunctionStateMachine:
        Type: "AWS::StepFunctions::StateMachine"
        Properties:
            StateMachineName: AthenaQueryExecute
            StateMachineType: STANDARD
            Fn::Transform:
                Name: AWS::Include
                Parameters:
                    Location: !Sub "s3://${CFnResourceBucket}/stepfunctions/create_datamart.yaml"
            RoleArn: !GetAtt StepFunctionServiceRole.Arn
        Metadata:
            "AWS::CloudFormation::Designer":
                id: 03217ee1-4cfd-4fee-804c-7a35f8901f6c
    # EventBridge Scheduler
    StepFunctionExecutionSchedule:
        Type: "AWS::Scheduler::Schedule"
        Properties:
            Description: AthenaQueryExecute StepFunction Daily Excecution
            ScheduleExpression: "cron(0 1 * * ? *)"
            FlexibleTimeWindow:
                Mode: FLEXIBLE
                MaximumWindowInMinutes: 15
            Name: AthenaQueryDailyExecution
            Target:
                Arn: !Ref StepFunctionStateMachine
                RoleArn: !GetAtt StepFunctionServiceRole.Arn
Metadata:
    "AWS::CloudFormation::Designer":
        03217ee1-4cfd-4fee-804c-7a35f8901f6c:
            size:
                width: 60
                height: 60
            position:
                x: 60
                "y": 90
            z: 1
            embeds: []
