AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a Step Functions state machine.
Resources:
    StepFunctionServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: HelloWorldEasy
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - states.amazonaws.com
                              - scheduler.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns: [arn:aws:iam::aws:policy/AdministratorAccess]
    StepFunctionStateMachine:
        Type: "AWS::StepFunctions::StateMachine"
        Properties:
            StateMachineName: HelloWorldEasy
            StateMachineType: STANDARD
            DefinitionS3Location:
                Bucket: quark-cicd-test
                Key: stepfunctions/HelloWorld-easy.yml
            RoleArn: !GetAtt StepFunctionServiceRole.Arn
        Metadata:
            "AWS::CloudFormation::Designer":
                id: 03217ee1-4cfd-4fee-804c-7a35f8901f6c
    StepFunctionExecutionSchedule:
        Type: "AWS::Scheduler::Schedule"
        Properties:
            Description: HelloWorldEasy StepFunction Excecution Schedule
            ScheduleExpression: "cron(0 1 * * ? *)"
            FlexibleTimeWindow:
                Mode: FLEXIBLE
                MaximumWindowInMinutes: 60
            Name: HelloWorldEasyEverydayExecution-for-CloudFormation
            Target:
                Arn: !GetAtt StepFunctionStateMachine.Arn
                RoleArn: !GetAtt StepFunctionServiceRole.Arn
Metadata:
    "AWS::CloudFormation::Designer":
        03217ee1-4cfd-4fee-804c-7a35f8901f6c:
            size:
                width: 60
                height: 60
            position:
                x: 60
                "y": 90
            z: 1
            embeds: []
